CLASSES = {
    "__background__": 0,
    "stillage_close": 1,
    "stillage_open": 2,
    "l_klt_6147": 3,
    "l_klt_8210": 4,
    "l_klt_4147": 5,
    "pallet": 6,
    "jack": 7,
    "forklift": 8,
    "str": 9,
    "bicycle": 10,
    "dolly": 11,
    "exit_sign": 12,
    "fire_extinguisher": 13,
    "spring_post ": 14,
    "locker": 15,
    "cabinet": 16,
    "cardboard_box": 17,
}
