CLASSES = [
    "stillage_close",
    "stillage_open",
    "l_klt_6147",
    "l_klt_8210",
    "l_klt_4147",
    "pallet",
    "jack",
    "forklift",
    "str",
    "bicycle",
    "dolly",
    "exit_sign",
    "fire_extinguisher",
    "spring_post",
    "locker",
    "cabinet",
    "cardboard_box",
]


CLASSES_DICT = {
    "stillage_close": 0,
    "stillage_open": 1,
    "l_klt_6147": 2,
    "l_klt_8210": 3,
    "l_klt_4147": 4,
    "pallet": 5,
    "jack": 6,
    "forklift": 7,
    "str": 8,
    "bicycle": 9,
    "dolly": 10,
    "exit_sign": 11,
    "fire_extinguisher": 12,
    "spring_post": 13,
    "locker": 14,
    "cabinet": 15,
    "cardboard_box": 16,
}
